WHITELIST = [
    "google.com", "bing.com", "yandex.ru", "duckduckgo.com", "yahoo.com",
    "vk.com", "instagram.com", "facebook.com", "twitter.com", "x.com",
    "tiktok.com", "linkedin.com", "pinterest.com", "reddit.com", "telegram.org",
    "discord.com", "snapchat.com", "tumblr.com", "twitch.tv",
    "youtube.com", "youtu.be", "rutube.ru", "vimeo.com", "dailymotion.com",
    "mail.ru", "gmail.com", "outlook.com", "yahoo.com", "proton.me",
    "rambler.ru", "inbox.ru", "yandex.ru",
    "github.com", "gitlab.com", "bitbucket.org", "stackoverflow.com",
    "leetcode.com", "hackerrank.com", "codewars.com", "codeforces.com",
    "replit.com", "codesandbox.io", "vercel.com", "netlify.com",
    "npmjs.com", "pypi.org", "hub.docker.com",
    "wikipedia.org", "docs.python.org", "developer.mozilla.org",
    "w3schools.com", "geeksforgeeks.org", "medium.com", "habr.com",
    "coursera.org", "udemy.com", "stepik.org", "khanacademy.org",
    "amazon.com", "ebay.com", "aliexpress.com", "ozon.ru", "wildberries.ru",
    "avito.ru", "dns-shop.ru", "mvideo.ru", "eldorado.ru",
    "sberbank.ru", "tinkoff.ru", "vtb.ru", "alfabank.ru", "raiffeisen.ru",
    "paypal.com", "stripe.com",
    "rbc.ru", "ria.ru", "lenta.ru", "kommersant.ru", "meduza.io",
    "bbc.com", "cnn.com", "reuters.com", "nytimes.com",
    "apple.com", "icloud.com", "microsoft.com", "office.com",
    "live.com", "onedrive.com", "google.ru",
    "canva.com", "figma.com", "notion.so", "trello.com", "slack.com",
    "zoom.us", "meet.google.com", "dropbox.com", "drive.google.com",
    "translate.google.com", "maps.google.com", "2gis.ru",
]
